version: "2"

tasks:
  default:
    cmds:
      - echo "No default task."
    silent: true

  start:
    cmds:
      - docker-compose --file pypi-server/Docker-compose.yaml up

  bootstrap:
    cmds:
      - brew install pipenv
      - pip3 install pre-commit
      - pre-commit install
      - pipenv install --dev

  compile_proto:
    cmds:
      - pipenv run python -m grpc_tools.protoc
        -IgRPC/protos/
        --python_out=gRPC/protolib/protolib
        --grpc_python_out=gRPC/protolib/protolib
        myprotos.proto

  # $ python -m grpc_tools.protoc -I../../protos --python_out=. --grpc_python_out=. ../../protos/route_guide.proto

  test:
    cmds:
      - echo "No tests."
    silent: true
