version: "2"

tasks:
  default:
    cmds:
      - echo "No default task."
    silent: true

  start:
    cmds:
      - docker-compose --file pypi-server/Docker-compose.yaml up

  bootstrap:
    cmds:
      - brew install pipenv
      - pip3 install pre-commit
      - pre-commit install
      - pipenv install --dev

  test:
    cmds:
      - echo "No tests."
    silent: true
