version: "3.3"
services:
  pypi-server:
    image: pypiserver/pypiserver:latest
    ports:
      - "8080:8080"
    container_name: pypi-server
    volumes:
      - type: bind
        source: ./auth
        target: /data/auth
      - type: volume
        source: ./packages
        target: /data/packages
    # See https://hub.docker.com/r/pypiserver/pypiserver to enable auth
    # command: -P /data/auth/.htpasswd -a update,download,list /data/packages
    restart: always
volumes:
  pypi-server:
  packages:
